# Generated by Django 3.2.18 on 2023-04-03 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(max_length=42, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("chain", models.CharField(choices=[("ETH", "eth")], max_length=16)),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("MAINNET", "mainnet"),
                            ("SEPOLIA", "sepolia"),
                            ("GOERLI", "goerli"),
                        ],
                        default="MAINNET",
                        max_length=100,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "owner_organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
