# Generated by Django 3.2.18 on 2023-06-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "smartcontract",
            "0002_rename_owner_organisation_smartcontract_owner_organization",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="smartcontract",
            name="abi",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
