# Generated by Django 3.2.18 on 2023-06-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartcontract", "0003_smartcontract_abi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smartcontract",
            name="abi",
            field=models.TextField(default=None, null=True),
        ),
    ]
