# Generated by Django 3.2.23 on 2023-12-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartcontract", "0006_alter_smartcontract_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smartcontract",
            name="chain",
            field=models.CharField(
                choices=[("ETH", "eth"), ("ARB", "arb")], max_length=16
            ),
        ),
    ]
