# Generated by Django 3.2.23 on 2023-12-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontract', '0008_alter_smartcontract_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='chain',
            field=models.CharField(choices=[('ETH', 'eth'), ('ARB', 'arb'), ('MNT', 'mnt'), ('SCRL', 'scrl')], max_length=16),
        ),
    ]
