version: '3.1'

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .pgadmin.env
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      default:
      internal:

volumes:
  pgadmin:
