# Generated by Django 3.2.18 on 2023-04-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerts",
            name="name",
            field=models.CharField(default="default", max_length=255),
            preserve_default=False,
        ),
    ]
