# Generated by Django 3.2.18 on 2023-04-06 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0002_alter_alerts_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "Sms"),
                            ("WEBHOOK", "Webhook"),
                        ],
                        default="EMAIL",
                        max_length=16,
                    ),
                ),
                ("notification_body", models.TextField(blank=True, null=True)),
                ("notification_target", models.CharField(max_length=255)),
                (
                    "trigger_transaction_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.alerts",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
