# Generated by Django 3.2.18 on 2023-04-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="meta_logs",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
