# Generated by Django 3.2.18 on 2023-04-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0004_auto_20230406_2358"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_body",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
