# Generated by Django 3.2.19 on 2023-11-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0005_alter_notification_notification_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerts",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
